name: Semgrep (Local Scan Only)

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  semgrep:
    name: Semgrep Local SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep scan
        run: |
          semgrep scan --config auto --json > semgrep-results.json
          cat semgrep-results.json

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json
